export const topics = [
  '3D printing',
  'A cappella singing',
  'Abandoned building photography',
  'Aboriginal dot painting',
  'Aerial silks',
  'AI prompts',
  'Air plant care',
  'Airbrush art',
  'Algae cultivation',
  'Alpaca farming',
  'Amateur radio',
  'Ancient coin collecting',
  'Annotating books',
  'Ant keeping',
  'Antique map collecting',
  'Appalachian Trail',
  'Aquaponics',
  'Aquariums',
  'Arcade restoration',
  'Archaeological surveys',
  'Arduino',
  'Arena polo',
  'Arrowhead collecting',
  'ASCII art',
  'Astronomy',
  'Astrophotography',
  'Aura farming',
  'Avalanche safety',
  'Axe throwing',
  'Axolotl grooming',
  'Backgammon',
  'Backrooms',
  'Backyard hens',
  'Bagpipe playing',
  'Balalaika playing',
  'Banjo playing',
  'Barbershop quartet',
  'BASE jumping',
  'Basket weaving',
  'Bass fishing',
  'Bat watching',
  'Bathtub racing',
  'Batik fabric dyeing',
  'BBQ',
  'Bean-to-bar chocolate making',
  'Beatboxing',
  'Bed racing',
  'Bee propolis collecting',
  'Beekeeping',
  'Best local dining',
  'Bicycle touring',
  'Bird law',
  'Bird watching',
  'Blacksmithing',
  'BMX',
  'Board game design',
  'Bobsledding',
  'Bocce ball',
  'Bodhran playing',
  'Bonsai trees',
  'Book folding art',
  'Bookbinding',
  'Books to read',
  'Boomer slang',
  'Boomerang throwing',
  'Botanical illustration',
  'Bread sculpting',
  'Break dancing',
  'Brush pen calligraphy',
  'Bullet journaling',
  'Bushcraft',
  'Butterfly breeding',
  'Butterfly gardening',
  'Cactus & succulent collecting',
  'Cajon playing',
  'Cake decorating',
  'Calligraphy',
  'Camel racing',
  'Camera obscura exploration',
  'Candle making',
  'Canoe tripping',
  'Canyoneering',
  'Card magic',
  'Cardboard boat racing',
  'Carillon bell ringing',
  'Carnivorous plant growing',
  'Cast iron cookware restoration',
  'Cave diving',
  'Cave exploration',
  'Cave painting recreation',
  'Cemetery photography',
  'Ceramic glaze chemistry',
  'Chado',
  'Chainsaw carving',
  'Chalk art',
  'Chameleon keeping',
  'Chapman stick',
  'Charcuterie board design',
  'Cheese aging',
  'Cheese making',
  'Cherry blossom tracking',
  'Chess',
  'Chicken keeping',
  'Chocolate tempering',
  'Cinemagraph creation',
  'Circuit bending',
  'Claymation',
  'Cloud spotting',
  'CNC milling',
  'Coasteering',
  'Cocktails',
  'Coffee brewing methods',
  'Coffee roasting',
  'Coin collecting',
  'Cold brew experimentation',
  'Comic book drawing',
  'Commonplace book keeping',
  'Companion planting',
  'Competitive casting',
  'Competitive eating',
  'Competitive whistling',
  'Competitive yo-yo',
  'Composting',
  'Concertina playing',
  'Concerts',
  'Contact juggling',
  'Cookie decorating',
  'Copperplate calligraphy',
  'Corn husk doll making',
  'Cornhole',
  'Covered bridge touring',
  'Crocheting',
  'Croquet',
  'Cross-country skiing',
  'Crossword puzzles',
  'Cryptic crossword solving',
  'Crystal growing',
  'Culinary history',
  'Cup and ball',
  'Curling',
  'Cycle polo',
  'Darkroom development',
  'Dart frog keeping',
  'Debate bro tactics',
  'Decoupage',
  'Desert exploration',
  'Diabolo',
  'Didgeridoo playing',
  'Digital illustration',
  'Disc golf',
  'Djembe drumming',
  'Dog grooming',
  'Dog sledding',
  'Double exposure photography',
  'Dragonfly watching',
  'Drone photography',
  'Drone racing',
  'Duck herding',
  'Duck keeping',
  'Dulcimer playing',
  'Egg decorating',
  'Elephant polo',
  'Embroidery',
  'Encaustic painting',
  'Engraving',
  'Erhu playing',
  'Escape room design',
  'Escape rooms',
  'Espresso dialing-in',
  'Etching',
  'Ethnic grocery stores',
  'Extreme ironing',
  'Falconry',
  'Fan fiction',
  'Felt puppet making',
  'Fermentation',
  'Ferret care',
  'Fife & drum corps',
  'Figure skating',
  'Film photography',
  'Fire dancing',
  'Fire starting techniques',
  'Firefly watching',
  'First edition books',
  'Fish printing',
  'Flint knapping',
  'Fly fishing',
  'Fog photography',
  'Food blogging',
  'Food photography',
  'Food science',
  'Food styling',
  'Footbag',
  'Foraging',
  'Formicarium',
  'Fossil casting',
  'Fossil hunting',
  'Found poetry',
  'Fountain pens',
  'Freediving',
  'Freestyle rap',
  'Fresco painting',
  'Funko Pop',
  'Gamelan music',
  'Generative art',
  'Geocaching',
  'Geode cracking',
  'GIFs',
  'Gilding',
  'Glacier hiking',
  'Glamping',
  'Glassblowing',
  'Goat keeping',
  'Gold panning',
  'Goo Goo Dolls songs',
  'Gourd carving',
  'Graffiti lettering',
  'Grass touching',
  'Gyotaku',
  'Hacky sack',
  'Haiku writing',
  'Hair styles',
  'Hammered dulcimer',
  'Hammock camping',
  'Hanami',
  'Hand bell ringing',
  'Hand lettering',
  'Hang drum playing',
  'Hang gliding',
  'Hedgehog care',
  'Herb drying & blending',
  'Hiking',
  'Home automation',
  'Home viticulture',
  'Homebrewing beer',
  'Homemade pasta',
  'Horseshoe pitching',
  'Hot air ballooning',
  'Hot sauce making',
  'Hot spring bathing',
  'Hurdy-gurdy playing',
  'Hydroponics',
  'Ice fishing',
  'Ice lantern making',
  'Ice sculpting',
  'Ice skating',
  'Icon painting',
  'Ikebana',
  'Infrared photography',
  'Inline skating',
  'Interview prep',
  'Jam & jelly making',
  'Japanese flower arranging',
  'Japanese woodworking',
  'Jaw harp',
  'Jazz music',
  'Jellyfish aquariums',
  'Jigsaw puzzles',
  'Juggling',
  'Kabaddi',
  'Kansas?',
  'Kazoo orchestras',
  'Kendama',
  'Kite flying',
  'Kite surfing',
  'Knife sharpening',
  'Knife throwing',
  'Knitting',
  'Koala comedy',
  'Koi pond designing',
  'Kombucha brewing',
  'Koto playing',
  'Kubb',
  'Lace making',
  'Lap steel guitar',
  'Laser cutting',
  'Latte art',
  'Lawn mower racing',
  'Leaf peeping',
  'Leatherworking',
  'Legal briefs',
  'LEGO',
  'Letterpress printing',
  'Lichen study',
  'Life hacks',
  'Liger videos',
  'Lighthouse visiting',
  'Linocut printmaking',
  'Lip sync battles',
  'Llama trekking',
  'Log rolling',
  'Logic puzzle solving',
  'Logical fallacies',
  'Long exposure photography',
  'Longboarding',
  'Looksmaxxing tips',
  'Luge',
  'Lure making',
  'Macramé',
  'Macro photography',
  'Magic tricks',
  'Magnetic poetry',
  'Mahjong',
  'Mandolin playing',
  'Marble racing',
  'Marching band',
  'Marginalia',
  'Marine biology',
  'Marionette making',
  'Matcha whisking',
  'Mead making',
  'Mechanical keyboards',
  'Memory jar keeping',
  'Menu design',
  'Metal casting',
  'Metal detecting',
  'Metallurgy',
  'Meteor shower watching',
  'Meteorite hunting',
  'Micro-meditation',
  'Mineral collecting',
  'Miniature book collecting',
  'Miniature horse breeding',
  'Miniature painting',
  'Mixology',
  'Model railroading',
  'Model rocketry',
  'Mosaic art',
  'Moss gardens',
  'Moth photography',
  'Motion graphics',
  'Mountain biking',
  'Mountaineering',
  'Movies to watch',
  'Mushroom cultivation',
  'Mushroom foraging',
  'Mushroom tea brewing',
  'Musical glasses',
  'Musical saw playing',
  'Nature journaling',
  'Needlepoint',
  'News bloopers',
  'Night photography',
  'Nikon cameras',
  'Nordic combined',
  'Northern lights',
  'Note-taking apps',
  'Numismatics',
  'Obscure subreddits',
  'Open water swimming',
  'Open-source software',
  'Operating systems',
  'Optical illusions',
  'Optimizing sleep',
  'Oral history recording',
  'Orchid cultivation',
  'Orienteering',
  'Origami tessellation',
  'Origami',
  'Ostrich racing',
  'Otamatone playing',
  'Owl watching',
  'Paddleboarding',
  'Panoramic photography',
  'Paper airplane design',
  'Paper marbling',
  'Paragliding',
  'Paris',
  'Parkour',
  'Peacock domestication',
  'Pedal steel guitar',
  'Permaculture',
  'Pétanque',
  'Pewter casting',
  'Philately',
  'Photo book making',
  'Pickling & preserving',
  'Pigeon racing',
  'Pinball machines',
  'Pinewood derby',
  'Ping-pong tournaments',
  'Pinhole camera building',
  'Pipe organ restoration',
  'Pixel art',
  'Plankton photography',
  'Podcast production',
  'Podcasts to listen to',
  'Poi spinning',
  'Pointillism',
  'Polo',
  'Postcard collecting',
  'Pottery',
  'Pour-over coffee obsession',
  'Praying mantis keeping',
  'Pressed flower art',
  'Puddle reflection photography',
  'Puzzle box making',
  'Pyrography',
  'Pysanky',
  'Quail farming',
  'Quilting',
  'Quoits',
  'Rabbit showing',
  'Radio astronomy',
  'Radio drama writing',
  'Rainbow chasing',
  'Ramen broth crafting',
  'Rare plant trading',
  'Raspberry Pi',
  'Recipe development',
  'Reddit saves',
  'Remote-control boats',
  'Remote-control cars',
  'Resin casting',
  'Restaurant history research',
  'Restaurants',
  'Retro computing',
  'Retro gaming',
  'Rewilding',
  'Rhythmic gymnastics',
  'River rafting',
  'Road cycling',
  'Robot companions',
  'Rock climbing',
  'Rock tumbling',
  'Rockhounding',
  'Roller derby',
  'Rooftop gardening',
  'Rooftop tent camping',
  'Rubber duck collecting',
  'Rubber duck racing',
  'Rube Goldberg machine building',
  'Saltwater fishing',
  'Sand art',
  'Sand castle building',
  'Sandwiches',
  'Satellite tracking',
  'Scale models',
  'Scrabble',
  'Scrapbooking',
  'Screen printing',
  'Scuba diving',
  'Sea glass collecting',
  'Sea kayaking',
  'Seed saving',
  'Sepak takraw',
  'Shadow photography',
  'Shadow puppetry',
  'Shamisen playing',
  'Shortwave listening',
  'Sick memes',
  'Silhouette photography',
  'Sitar playing',
  'Skateboarding',
  'Ski jumping',
  'Skydiving',
  'Slow travel',
  'Smooth operating',
  'Snail racing',
  'Snorkeling',
  'Snow globes',
  'Snow sculpture',
  'Snowboarding tricks',
  'Snowshoeing',
  'Soap box derby',
  'Soap making',
  'Social media links',
  'Soil science',
  'Solar observation',
  'Soldering',
  'Sourdough bread baking',
  'Spearfishing',
  'Speed cubing',
  'Spelunking',
  'Spice blending',
  'Spinning yarn',
  'Spoons playing',
  'Staff spinning',
  'Stained glass making',
  'Stamp collecting',
  'Stand-up comedy',
  'Stand-up paddleboard yoga',
  'Star gazing',
  'Steel drum',
  'Stick insect keeping',
  'Stilt walking',
  'Stop-motion animation',
  'Storm chasing',
  'Storytelling',
  'Stylophone',
  'Sudoku',
  'Sugar sculpture',
  'Sushi making',
  'Swamp tours',
  'Synchronized swimming',
  'Tabla drumming',
  'Tabletop RPG',
  'Taiko drumming',
  'Tarantula keeping',
  'Taxidermy fish mounting',
  'Taxidermy',
  'Tea ceremony',
  'Tech articles to read',
  'Telescopes',
  'Terrarium building',
  'Theremin playing',
  'Thru-hiking',
  'Thunderstorm watching',
  'Tide pool exploration',
  'Tide watching',
  'Tight rope walking',
  'Timelapse photography',
  'Tole painting',
  'Tortoise keeping',
  'Tourism',
  'Traditional sumi-e ink painting',
  'Trail running',
  'Train travel',
  'Trapeze',
  'Travel journaling',
  'Typewriter poetry',
  'Ukulele playing',
  'Ultimate frisbee',
  'Ultramarathons',
  'Underwater hockey',
  'Underwater photography',
  'Unfrozen caveman law',
  'Unicycling',
  'Urban sketching',
  'Urbex',
  'Van life',
  'Vanilla cultivation',
  'Ventriloquism',
  'Vermicomposting',
  'Via ferrata',
  'Vibe surgery',
  'Video game preservation',
  'Viking chess',
  'Vintage cookware collecting',
  'Vintage recipes',
  'Vintage typewriters',
  'Vintage watch collecting',
  'Vinyl records',
  'Voice acting',
  'Volcano tourism',
  'Water kefir brewing',
  'Watercolor painting',
  'Waterfall chasing',
  'Weather stations',
  'Weaving',
  'Webcomic authoring',
  'Whale watching',
  'Whitewater kayaking',
  'Wild camping',
  'Wilderness survival skills',
  'Wildlife tracking',
  'Wine making',
  'Winter camping',
  'Wood burning',
  'Wood turning',
  'Wordle strategies',
  'Wrestling',
  'Yarn theory',
  'Yo mama jokes',
  'Youtube watch later',
  'Zentangle drawing',
  'Zine making',
  "80's hair bands",
  "Rubik's cube solving",
];
